export const SYSTEM_CONSTANTS = {
  APP_NAME: 'OrgHub HRMS',
  DEFAULT_COUNTRY: 'IN',
  DEFAULT_CURRENCY: 'INR',
  DEFAULT_TIMEZONE: 'Asia/Kolkata',
  PAGINATION: {
    DEFAULT_PAGE_SIZE: 20,
    MAX_PAGE_SIZE: 100,
  },
  MAX_REPORTING_DEPTH: 25,
  SESSION: {
    IDLE_TIMEOUT_MINUTES: 30,
    ABSOLUTE_TIMEOUT_HOURS: 12,
  },
} as const;
