all:
  children:
    edge:
      hosts:
        edge-staging-01:
          ansible_host: 10.10.10.11
          keepalived_role: MASTER
          keepalived_priority: 101
        edge-staging-02:
          ansible_host: 10.10.10.12
          keepalived_role: BACKUP
          keepalived_priority: 100
      vars:
        edge_vip: 10.10.10.10

    app:
      hosts:
        app-staging-01:
          ansible_host: 10.10.20.21
        app-staging-02:
          ansible_host: 10.10.20.22

    workers:
      hosts:
        worker-staging-01:
          ansible_host: 10.10.20.25

    database:
      hosts:
        pg-staging-01:
          ansible_host: 10.10.30.31
          patroni_role: primary
        pg-staging-02:
          ansible_host: 10.10.30.32
          patroni_role: sync_standby
        pg-staging-03:
          ansible_host: 10.10.30.33
          patroni_role: replica
      vars:
        haproxy_vip: 10.10.30.30

    etcd:
      hosts:
        etcd-staging-01:
          ansible_host: 10.10.30.36
          etcd_member_name: etcd-01
        etcd-staging-02:
          ansible_host: 10.10.30.37
          etcd_member_name: etcd-02
        etcd-staging-03:
          ansible_host: 10.10.30.38
          etcd_member_name: etcd-03

    valkey:
      hosts:
        valkey-staging-01:
          ansible_host: 10.10.30.41
          valkey_role: master
        valkey-staging-02:
          ansible_host: 10.10.30.42
          valkey_role: replica

    storage:
      hosts:
        storage-staging-01:
          ansible_host: 10.10.30.51
        storage-staging-02:
          ansible_host: 10.10.30.52
        storage-staging-03:
          ansible_host: 10.10.30.53
        storage-staging-04:
          ansible_host: 10.10.30.54

    vault:
      hosts:
        vault-staging-01:
          ansible_host: 10.10.30.61
        vault-staging-02:
          ansible_host: 10.10.30.62
        vault-staging-03:
          ansible_host: 10.10.30.63

    backup:
      hosts:
        backup-staging-01:
          ansible_host: 10.10.40.71

    management:
      hosts:
        bastion-staging:
          ansible_host: 10.10.50.81
        monitor-staging:
          ansible_host: 10.10.50.82
        egress-staging:
          ansible_host: 10.10.50.83
