---
- name: Restart valkey-server
  ansible.builtin.systemd:
    name: redis-server
    state: restarted

- name: Restart valkey-sentinel
  ansible.builtin.systemd:
    name: redis-sentinel
    state: restarted
